In [12]:
from __future__ import print_function 
import torch
x = torch.Tensor(5,3)
x1 = torch.rand(5,3)    #创建不同形状的随机矩阵
x 

tensor([[3.5486e-18, 4.5559e-41, 3.5486e-18],
        [4.5559e-41, 6.9169e-01, 1.7900e+00],
        [1.3685e+00, 1.0897e-01, 7.0541e-01],
        [1.1366e+00, 7.4956e-01, 1.6054e+00],
        [1.1774e+00, 1.0025e+00, 7.4706e-01]])

In [2]:
x.size()

torch.Size([5, 3])

In [13]:
x1

tensor([[0.5485, 0.7410, 0.3882],
        [0.5657, 0.7194, 0.6859],
        [0.0033, 0.6657, 0.6802],
        [0.6450, 0.2225, 0.6908],
        [0.1307, 0.8957, 0.3540]])

In [6]:
y = torch.rand(5,3)
z = x + y
#torch.add(x,y)
z.type()

'torch.FloatTensor'

In [10]:
# 特别注明：任何可以改变tensor内容的操作都会在方法名后加一个下划线'_'
result = torch.Tensor(5,3)
result

tensor([[3.5486e-18, 4.5559e-41, 3.5486e-18],
        [4.5559e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [11]:
z

tensor([[1.5243, 1.2738, 0.5558],
        [1.4285, 0.6917, 1.7900],
        [1.3685, 0.1090, 0.7054],
        [1.1366, 0.7496, 1.6054],
        [1.1774, 1.0025, 0.7471]])

In [34]:
x.t_()

tensor([[0.6242, 0.8084, 0.4474],
        [0.6672, 0.6859, 0.8313],
        [0.9246, 0.0205, 0.6707],
        [0.9077, 0.3558, 0.7973],
        [0.6770, 0.7630, 0.2384]], device='cuda:0')

In [15]:
y

tensor([[0.6242, 0.8084, 0.4474],
        [0.6672, 0.6859, 0.8313],
        [0.9246, 0.0205, 0.6707],
        [0.9077, 0.3558, 0.7973],
        [0.6770, 0.7630, 0.2384]])

In [25]:
a = torch.ones(5)
b = a.numpy()

In [32]:
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [27]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [31]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out = a )

array([2., 2., 2., 2., 2.])

In [36]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    

In [37]:
z 

tensor([[1.2483, 1.6168, 0.8949],
        [1.3344, 1.3718, 1.6626],
        [1.8491, 0.0411, 1.3413],
        [1.8155, 0.7117, 1.5946],
        [1.3540, 1.5261, 0.4769]], device='cuda:0')

In [38]:
torch.cuda.is_available()

True

In [47]:
from torch.autograd import Variable 
x = Variable(torch.ones(2,2),requires_grad = True)
y = x + 2
#y.creator
z = y*y*3
out = z.mean()

In [50]:
out.backward()

In [51]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [74]:
x = torch.FloatTensor([-2.1684, -0.0643 , 0.8492])
x = Variable(x, requires_grad = True)
y = x * 2
while y.norm() < 1000:
    y = y * 2
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
#y.backward(torch.Tensor(3,1))
y.backward(gradients)
x.grad


tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])

In [68]:
gradients

tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])

In [84]:
import torch.nn as nn 
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.conv1 = nn.Conv2d(1,6,5)
        self.conv2 = nn.Conv2d(6,16,5)
        self.fc1 = nn.Linear(16*5*5,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3   = nn.Linear(84, 10)
        
    def forward(self,x):
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)),2)
        x = x.view(-1,self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self,x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    
net = Net()
net 


Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

In [79]:
params = list(net.parameters())
print(len(params))

10


In [80]:
print(params[0].size())

torch.Size([6, 1, 5, 5])


In [95]:
input = Variable(torch.randn(1,1,32,32))
out = net(input)
print(out)

tensor([[ 0.0114,  0.1414, -0.0406,  0.0852, -0.0664, -0.0638, -0.0630,  0.0084,
          0.0254,  0.0764]], grad_fn=<AddmmBackward>)


In [96]:
net.zero_grad()
out.backward(torch.randn(1,10))

In [100]:
target = Variable(torch.range(1,10))
criterion = nn.MSELoss()


NameError: name 'conv1' is not defined

In [1]:
###新笔记
import torch
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [2]:
y = x+2
y.grad_fn

In [3]:
z = torch.mean(y*y)
z.data

tensor(9.)

In [5]:
z.backward()
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


In [8]:
#http://capitalbikeshare.com/system-data 共享单车的数据
#www.freemeteo.com 对数据可以进行独热编码
#因为有些属性不是数值类型或者大小含义不等，要先预处理
#类型数据（星期几）独热编码，N个类型，一种一个置为1，其他0
#数值变量，假设正态分布进行标准化
#时间横移的数据就变成一个圆柱体

input_size = 59    #处理后的特征属性,输入单元
hidden_size = 10 
output_size = 1
batch_size = 128   #分批
neu = torch.nn.Sequential(
    torch.nn.Linear(input_size,hidden_size),
    torch.nn.Sigmoid(),
    torch.nn.Linear(hidden_size,output_size),
)
cost = torch.nn.MSELoss()        #等价于torch.mean((y-y*)^2) 预测问题一般用的
                                    #均方差误差
optimizer = torch.optim.SGD(net.parameters(),lr=0.01)

for i in range(2000):
    batch_loss = [] #记录每一个batch的损失
    #128个样本点被分为一个batch
    for start in range(0,len(X),batch_size):
        end = start + batch_size if start + batch_size < len(X) else len(X)
        xx = Varialble(torch.FloatTensor(X[start:end]))
        yy = Variable(torch.FloatTensor(Y[start:end]))
        predict = neu(xx)         #模型预测
        loss = cost(predict,yy)
        optimizer.zero_grad()    #优化器存储梯度置0
        loss.backward()
        optimizer.step()   #优化器开始运行一步，更新所有的参数
        batch_loss.append(loss.data.numpy())  #加上这一步的loss值
    if i%100 ==0:
        losses.append(np.mean(batch_loss))
        print(i,np.mean(batch_loss))

NameError: name 'X' is not defined

In [ ]:
#文本分类问题
#词袋模型，对语料库中的所有单词排序，语料有多少词，向量就有多少维度，对于一个句子
#统计出每一个单词的出现次数，并将这个数字填充到相应位置，出现次数除以这句话中的总
#次数
model = nn.Sequencial(
    nn.Linear(7139,10),   #7139个单词
    nn.ReLU(),
    nn.Linear(10,2),
    nn.LogSoftmax(dim = 1),
) 

cost = torch.nn.NLLLoss()   #分类问题一般用的交叉熵损失
optimizer = torch.optim.Adam(model.parameters(),lr=0.01)
records = []
losses = []

for epoch in range(10):
    for i,data in enumerate(zip(train_data,train_label)):
        #enumerate(sequence, [start=0]) 组合成一个索引序列
        #zip把可迭代对象打包成一个元组，zip（*x）是反向的过程
        x,y = data
        x = Variable(torch.FloatTensor(x).view(1,-1)) 
        #view函数是将多行的tensor拼成一行
        y = Variable(torch.LongTensor(np.array([y])))  #这儿也不是很懂为什么要【y】
        
        optimizer.zero_grad()
        predict = model(x)
        loss = cost(predict,y)
        losses.append(loss.data.numpy()[0])    #这里不是很懂为什么要加上【0】
        loss.backward()
        optimizer.step()
        
if i%3000 ==0:
    val_losses = []
    rights = [] #在校验集上进行试验
    for j,val in enumerate(zip(valid_data,valid_label)):
        x,y = val
        x = Variable(torch.FloatTensor(x).view(1,-1))
        y = Variable(torch.LongTensor(np.array([y])))
        predict = model(x)
        #调用rightness函数来计算准确率
        right = rightness(predict,y)
        rights.append(right)
        loss = cost(predict,y)
        val_losses.append(loss.data.numpy()[0])
        #计算平均准确度
        right_ratio = 1.0*np.sum([i[0] for i in rights])/np.sum([i[1] for i in rights])   
        #这里不是很懂为什么sum（）里要加上【】
        print("第{}轮，训练损失：{:.2f},校验损失：{:.2f},校验准确率：{:.2f}".format
             (epoch,np.mean(losses),np.mean(val_losses),right_ratio))
        #Python2.6 开始，新增了一种格式化字符串的函数 str.format()，
        #它增强了字符串格式化的功能。基本语法是通过 {} 和 : 来代替以前的 % 。
        
        records.append([np.mean(losses),np.mean(val_losses),right_ratio])
        
#文本分类-词袋模型-神经网络分类器的实现-训练集校验集和测试集    
    

In [18]:
#卷积神经网络
#卷积核，越白表示权重越大，是看原始图像和卷积核的相似程度。
#在表示的时候可以把最后得到的很多个特征图拼在一起组成一个立方体
#池化操作是在每一个窗口中取一根最大值得到一个新图像，作用是模糊化获取更粗线条的信息
#然后再卷积，再池化
#最后特征图拉平成一个一维向量，然后全连接一个前馈网络，最后连一个logsoftmax层，得到
#每一个类别的概率对数值
import torchvision.datasets as dsets
import torchvision.transforms as transforms

train_dataset = dsets.MNIST(root='./data',#文件存放路径
                            train = True,
                            transform = transforms.ToTensor(),
                            download = True)
test_dataset = dsets.MNIST(root = './data',
                            train = False,
                            transform = transforms.ToTensor())
#数据集的加载
train_loader = torch.utils.data.DataLoader(dataset = train_dataset,
                                          batch_size = batch_size,
                                          shuffle = True)
test_loader = torch.utils.data.DataLoader(dataset = test_dataset,
                                         batch_size = batch_size,
                                          shuffle = False)

In [22]:
#分离校验集，采样器
indices = range(len(test_dataset))
indices_val = indices[:5000]        #校验数据集
indices_test = indices[5000:]

#构造采样器
sampler_val = torch.utils.data.sampler.SubsetRandomSampler(indices_val)
sampler_test = torch.utils.data.sampler.SubsetRandomSampler(indices_test)

validation_loader = torch.utils.data.DataLoader(dataset = test_dataset,
                                               batch_size = batch_size,
                                               #shuffle = True,
                                               sampler = sampler_val)

test_loader = torch.utils.data.DataLoader(dataset = test_dataset,
                                         batch_size = batch_size,
                                         #shuffle = True,
                                         sampler = sampler_test)

In [24]:
import torch.nn.functional as F
import torch.nn as nn

class ConvNet(torch.nn.Module):
    def __init__(self):
        super(ConvNet,self).__init__()
        self.conv1 = nn.Conv2d(1,4,5,padding = 2)
        #黑白，输入通道为1，输出通道（卷积核的个数），5是窗口的大小
        self.pool = nn.Maxpool2d(2,2)
        #2是池化的窗口大小
        self.conv2 = conv2d(4,8,5,padding = 2)
        self.fc1 = nn.Linear(image_size//4 * image_size //4 *8,512) 
        # 是地板除的意思,两个2池化被8个输出通道拉平，传给512
        self.fc2 = nn.Linear(512,num_classes)
        
    def forward(self,x):
        x = F.relu(self.conv1(x))
        x = self.pool(x)
        x = F.relu(self.conv2(x))
        x = self.pool(x)
        x = x.view(-1, image_size // 4* image_size//4 * 8)
        #不知道和（-1,1）有什么区别
        x = F.relu(self.fc1(x))
        x = F.dropout(x,training = self.training)  
        #这个函数不太懂,dropout是在训练过程中随机的删除一些连边的情况来增加鲁棒性，
        #drop率可为0.5，且只在训练时候使用，在测试的时候不使用
        #是防止过拟合的技术
        x = self.fc2(x)
        x = F.log_softmax(x)
        return x
        

In [ ]:
for epoch in range(num_epochs):
    for batch_idx, (data,target) in enumerate(train_loader):
        data, target = Variable(data), Variable(target)
        #模型在训练集上训练
        net.train()   #打开training变量
        output = net(data)
        
        loss = criterion(output,target)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if batch_idx %100 == 0:
            #打印和记录数据
            net.eval()
            val_rights = []
            for (data,target) in validation_loader:
                data,target = Variable(data),Variable(target)
               
                output = net(data)
                
                right = rightness(output,target)
                
            
            
net.eval()  
#关闭training 变量，打开的时候dropout才能发挥作用

#在测试集上运行
test.loss = 0 
correct = 0
for data,target in test_loader:
    data, target  = Variable(data), Variable(target)
    
    output = net(data)
    
    val = rightness(output, target)
    
#训练曲线要在校验曲线的上方（这个说法应该是不准确的，应该说是走势上不能有相反的动向）

In [25]:
#迁移学习允许训练集和测试集有不同的分布
#预训练模式，是迁移值作为初始值
#固定值模式，一直固定
#Hymenoptera genome database 224*224像素 彩色
#全部的数据只有224条样本
import torch 
import torch.nn as nn 
import torch.optim as optim 
from torch.autograd import Variable
import torch.nn.functional as F
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time 
import copy
import os 

In [ ]:
data_dir = "data"
image_size = 224
#从data_dir/train中加载文件
#1.随机从原始图像中切下来一块224*224区域
#2.随机水平翻转
#3.将图像的色彩数值标准化
train_dataset = datasets.ImageFolder(os.path.join(data_dir,"train"),
                                    transforms.Compose([
                                        transforms.RandomSizedCrop(image_size),
                                        transforms.RandomHorizaontalFlip(),
                                        transforms.ToTensor(),
                                        transforms.Normalize([0.485,0.456,0.406],
                                                            [0.229,0.224,0.225])
                                        
                                    ])
                                    )

#扩大到256，中心对称裁剪，转成张量，颜色标准化处理
val_dataset = datasets.ImageFolder(os.path.join(data_dir,"val"),
                                   transforms.Compose([
                                       transforms.Scale(256),
                                       transforms.CenterCrop(image_size),
                                       transforms.ToTensor(),
                                       transforms.Normalize([0.485,0.456,0.406],
                                                            [0.229,0.224,0.225])
                                   ])
                                  )
#创建相应的数据加载器
train_loader = torch.utils.data.DataLoader(train_dataset,batch_size=4,shuffle = True,
                                           num_workers = 4)
val_loader = torch.utils.data.DataLoader(val_dataset,batch_size = 4,shuffle=True,
                                         num_worker = 4)

num_classes = len(train_datasets.classes)

In [34]:
net = model.resnet18(pretrained = True)
#这一步可选,加上就变成了固定形
for param in net.parameters():
    param.requires_grad = False
    
#存储了最后两层神经元的输入神经元个数
num_ftrs = net.fc.in_features
net.fc = nn.Linear(num_ftrs,2)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(),lr=0.0001,momentum=0.9)  #动量法

AttributeError: 'Sequential' object has no attribute 'resnet18'

In [ ]:
#训练过程
record = []
num_epochs = 20
for epoch in range(num_epochs):
    train_rights = []
    train_losses = []
    for batch_idx,(data,target) in enumerate(train_loader):
        data,target = Variable(data),Variable(target)
        #完成一次预测
        output = net(data)
        loss = criterion(output,target)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        right = rightness(output,target)
        
        train_rights.append(right)
        train_losses.append(loss.data.numpy())
        
#这个上面的校验数据loss又是基本在训练数据的上方了
#迁移学习有望解决数据稀缺的问题，是神经网络的切分和组合

In [27]:
#图像风格迁移，生成一个随机噪声，然后在内容在相似一张图片，风格上相似另一张图片
#相似只是把两张图片输入到同一个CNN中，让其进行图层卷积，高层卷积出来的特征图是不是相同

#Lc(figure_1,figure_2)这个是高层特征图相似度，反映了内容上的相似程度
#低层特征图，再其基础上再计算一下gram矩阵（拉成一列然后自乘），就可以反应风格上的相似程度
#底层特征图需要把很多层加起来取平均

#最后得到一个L = αLc + βLs


#CNN的选取，选了VGG19（牛津视觉几何组，特点是卷积核小3*3，且网络很深），直接固定住就可以
#读入图片 === 读入VGG === 构造新的计算图 === 开始迭代优化

#添加了输入图像模块和风格损失和内容损失
import torch 
import torch.nn as nn 
import torch.optim as optim 
from torch.autograd import Variable

import torchvision
import torchvision.transforms as transforms
import torchvision.models as models
import copy 

#是否用GPU进行计算
use_cuda = torch.cuda.is_available()
dtype = torch.cuda.FloatTensor if use_cuda else torch.FloatTensor

In [28]:
#风格图像的路径，自行设定
style = 'images/escher.jpg'
#内容图像的路径
content = 'images/portrait1.jpg'

#图像大小相同

#定义两个权重
style_weight = 1000
content_weight = 1

#图像预处理
#缩放到相同的大小
#转化为Tensor

In [29]:
cnn = models.vgg19(pretrained = True).features
if use_cuda:
    cnn = cnn.cuda()

Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to /root/.torch/models/vgg19-dcbb9e9d.pth
574673361it [01:28, 6514303.70it/s] 


RuntimeError: CUDA error: out of memory

In [31]:
#内容损失模块(由于也是新的节点，所以也定义成神经网络结构)
class ContentLoss(nn.Module):
    def __init__(self,target,weight):  #target是目标图片经CNN提取的特征图
        super(ContentLoss,self).__init__()
        #目标图像的特征图和原始计算图分离
        self.target = target.detach()*weight
        self.weight = weight
        self.criterion = nn.MSELoss()
    def forward(self,input):    #input是原始噪声图片经CNN提取的特征图
        #输入的input是一个特征图
        #计算均方误差
        self.loss = self.criterion(input*self.weight, self.target)
        self.output = input
        return self.output
    def backward(retain_graph = retain_graph):
        #开始反向传播
        self.loss.backward(retain_graph = retain_graph)  #不是很理解
        return self.loss

NameError: name 'retain_graph' is not defined

In [32]:
class StyleLoss(nn.Module):
    def __init__(self,target,weight):
        super(StyleLoss,self).__init__()
        self.target = target.detach()*weight
        self.weight = weight
        self.criterion = nn.MSELoss()
    def forward(self,input):
        self.output = input.clone()
        input = input.cida() if use_cuda else input
        self_G = Gram(input)
        self_G.mul_(self.weight)
        #计算损失函数，即输入特征图的gram矩阵和目标特征图的gram矩阵之间的差异
        self.loss = self.criterion(self_G,self.target)
        return self.output
    def backward(self,retain_graph = True):
        #反向传播算法
        self.loss.backward(retain_graph = retain_graph)
        return self.loss

In [33]:
content_losses = []
style_losses = []
model = nn.Sequential()
#一个新的序贯网络模型

In [ ]:
i= 1
for layer in list(cnn):
    if isinstance(layer,nn.Conv2d):
        name = "conv_" + str(i)  #将已经加载的模块放到新的神经模块中去
        model.add_module(name,layer)
        
        if name in content_layers:
            #如果当前模型在定义好的要计算内容损失的层
            target = model(content_img).clone()
            #将内容图像当前层的feature信息拷贝到target中
            content_loss = ContentLoss(target, content_weight)
            #定义content_loss的目标函数
            content_loss = content_loss.cuda() if use_cuda else content_loss
            module.add("content_loss" +str(i),content_loss)
            #加上这么一层
            content_losses.append(content_loss)
            
        if name in style_layers:
            #如果当前层在指定的风格层中
            target_feature = model(style_img).clone()
            target_feature = target_feature.cuda() if use_cuda else target_feature
            traget_feature_gram = Gram(target_feature)
            style_loss = StyleLoss(target_feature_gram,style_weight)
            style_loss = style_loss.cuda() if use_cuda else style_loss
            model.add_module("style_loss_" +str(i),style_loss)
            style_losses.append(style_loss)
    
    #省略了其他的非卷积层一样的也是简单copy就可以    

In [35]:
#生成原始图像
input_img = Variable(torch.randn(content_img.data.size())).type(dtype)
if use_cuda:
    input_img = input_img.cuda()
    content_img = content_img.cuda()
    style_img = style_img.cuda()
    
#将选中的待调整图打印出来
plt.figure()
imshow(input_img.data,title="input Image")

NameError: name 'content_img' is not defined

In [36]:
#将输入图像变成神经网络的参数
input_param = nn.Parameter(input_img.data)

#定义优化器，采用LBFGS优化算法来优化
optimizer = optim.LBFGS([input_param])

NameError: name 'input_img' is not defined

In [ ]:
#每一个训练周期
#限制输入图像的色彩取值范围在0-1之间
input_param.data.clamp_(0,1)

#清空梯度
optimizer.zero_grad()
#将图像输入构造的神经网络中
model(input_param)
style_score = 0
content_score = 0
#每个损失函数层都开始反向传播
for sl in style_losses:
    style_score += sl.backward()
    
for cl in content_losses:
    content_score += cl.backward()
    
#一步优化(这里看出代码是不完整的，closure是包含上面操作的一个函数def)
optimizer.step(closure)


In [1]:
#镜像网络，生成对抗网络
#生成模型，猫鼠游戏，超分辨率重建，计算机脑补


#反卷积，和CNN是镜像的，它的反卷积核和卷积核是上下左右翻转后的关系，就是转置
#先是padding把两边用0补齐，然后再和反卷积核做卷积运算

#反池化，因为在有stride的卷积操作中当步长大于1的时候也同时会起到池化的作用
#所以在反卷积的时候就可以先对原图像进行填补格点来起到反池化的作用

#deconvolution，对于生成器来说希望loss越大越好
#对于判别器来说希望loss越小越好，所以当loss曲线进入剧烈振荡期的时候，就是在博弈的时候

In [2]:
class ModuleG(nn.Module):
    def __init__(self):
        super(ModuleG,self).__init__()
        self.model = nn.Sequential()
        #这里参数怎么传暂时还不清楚，尤其是dim的含义，和其他参数的含义
        #增加第一层反卷积
        self.model.add_module('deconv1',nn.ConvTranspose2d(input_dim,
                                    num_features*2,5,2,0,bias=False))
        #增加一个batchnorm层
        self.model.add_module('bnorm1',nn.BatchNorm2d(num_features*2))
        self.model.add_module('relu1',nn.ReLU(True))
        
        #第二层反卷积
        self.model.add_module('deconv2',nn.ConvTranspose2d(num_fetures*2,
                                    num_features,5,2,0,bias=False))
        self.model.add_module('bnorm2',nn.BatchNorm2d(num_features))
        self.model.add_module('relu2',nn.ReLU(True))
        
        #第三层反卷积
        self.model.add_module('deconv3',nn.ConvTranspose2d(num_features,
                                             num_chuannels,4,2,0,bias=False))
        self.model.add_module('sigmoid',nn.Sigmoid())
        
        
    def forward(self,input):
        output = input 
        for name,module in self.model.named_children():
            output = module(output)
        return(output)

SyntaxError: unexpected EOF while parsing (<ipython-input-2-7dbd5cc15421>, line 27)

In [ ]:
#从数据库中读取真实的图片 === 判别器判断 ==== 计算error_real === error_real.backward()
#随机产生一个噪声z ==== 生成器产生一组batch的图片 === 判别器判断 === 计算error_fake
# ==== error_fake.backward() === optimizerD.step()

#Random()<0.5 则继续否则退出  ==== 随机产生噪声z === 学好的生成器产生一组图片 ====
#判别器判断  ==== 计算error_G ===== error_G.backward() === optimizerG.step()


#1.将真实数据放到辨别网络里识别
output = netD(data)  #真实图片

#计算损失函数
label.data.fill_(1)   #因为是真的所以都是1
error_real = criterion(output,label)

#2.噪声生成图片
noise.data.resize_(data.size()[0], input_dim, 1,1).normal_(0,1)

#噪声是一个input_dim维度的向量
#喂给生成器生成图像
#这里的detach是为了让生成器不参与梯度更新
fake_pic = netG(noise).detach()

#用辨别器识别假图像
output2 = netD(fake_pic)
#标签是0，代表图片是伪造得到
label.data.fill_(0)

#计算损失函数
error_fake = criterion(ouput2,label)

In [ ]:
label.data.fill(1)  #分类标签全部为1，即真实图像
#重新随机生成一个噪声向量
noise.data.normal_(0,1)
netG.train()
#生成器进行伪造
fake_pic = netG(noise)

#辨别器进行分辨
output = netD(fake_pic)
#辨别器的损失函数
error_G = criterion(ouput,label)

#反向传播和优化网络
error_G.backward()
optimizerG.step()


#有一些细节，批正则化，优化算法，反卷积尺寸，网络初始化都忽略了

# 接下来是官方教程

In [22]:
#接下来是官方教程
from __future__ import print_function
import torch

In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [24]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.conv1 = nn.Conv2d(1,6,3)
        self.conv2 = nn.Conv2d(6,16,3)
        
        self.fc1 = nn.Linear(16*6*6,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)
        
    def forward(self,x):
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        
        x = F.max_pool2d(F.relu(self.conv2(x)),2)
        
        x = x.view(-1,self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self,x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
        

In [25]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [26]:
input = torch.randn(1,1,32,32)
out = net(input)
print(out)

tensor([[ 0.1109,  0.1164,  0.0358,  0.0668, -0.0648, -0.1617, -0.0863,  0.0604,
          0.0627, -0.0568]], grad_fn=<AddmmBackward>)


In [45]:
print(net.fc1.weight.grad)
print(net.fc1)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
Linear(in_features=576, out_features=120, bias=True)


In [44]:
net.zero_grad()
out.backward(torch.randn(1,10))

In [42]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])

## 更新权重

In [64]:
input = torch.randn(1,1,32,32)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1) 
criterion = nn.MSELoss()                   

import torch.optim as optim

optimizer = optim.SGD(net.parameters(),lr=0.01)
#清零
optimizer.zero_grad()

output = net(input)
loss = criterion(output,target)
loss.backward()
optimizer.step()

In [65]:
params = list(net.parameters())
len(params)

10

In [66]:
params

[Parameter containing:
 tensor([[[[ 0.0488, -0.0451,  0.0227],
           [ 0.3286,  0.2313, -0.1646],
           [ 0.2145,  0.2534, -0.2652]]],
 
 
         [[[-0.1296, -0.1138, -0.1765],
           [ 0.1043,  0.0154, -0.2794],
           [-0.1726, -0.1284, -0.3212]]],
 
 
         [[[ 0.0771,  0.2457, -0.0671],
           [ 0.0678,  0.1519, -0.3046],
           [-0.1106,  0.2578,  0.2564]]],
 
 
         [[[ 0.2772, -0.0563, -0.0297],
           [-0.2148,  0.2617, -0.1288],
           [-0.0211, -0.2802, -0.0217]]],
 
 
         [[[ 0.1374, -0.1174, -0.0939],
           [ 0.0863, -0.1869, -0.0781],
           [ 0.1784,  0.2484,  0.2489]]],
 
 
         [[[ 0.0495,  0.0908,  0.2680],
           [ 0.1280,  0.2069,  0.2212],
           [ 0.1324,  0.0902, -0.2895]]]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2375, -0.1166,  0.0898,  0.1557,  0.2206,  0.0691],
        requires_grad=True),
 Parameter containing:
 tensor([[[[ 9.2450e-02,  8.7556e-02,  5.6000e-02],
           [